server:
  # undertow
  undertow:
    accesslog:
      dir: ./log/ # Undertow access log directory.
      enabled: false # Enable access log.
      pattern: '%t [%I] %a %r %s (%b Byte) (%T ms)' # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
    buffer-size: # Size of each buffer in bytes.
    buffers-per-region: # Number of buffer per region.
    direct-buffers: # Allocate buffers outside the Java heap.
    io-threads: # Number of I/O threads to create for the worker.
    max-http-post-size: 0 # Maximum size in bytes of the HTTP post content.
    worker-threads: # Number of worker threads.
  port: 9002
  servlet:
    context-path: /video

spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  freemarker:
    suffix: .html
    request-context-attribute: request

  main:
    banner-mode: 'off'
master:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: false  #是否开启redis缓存  true开启   false关闭
  uploadPath: ./zFile/file
  isDayType: false

  imagePath: ./zFile/image/

logging:
  level:
    com.ibatis: info
    org.springframework.web: info
    com.winnerdt: info
